# Generated by Django 2.2.24 on 2023-02-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
