# Generated by Django 4.1.7 on 2023-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_rename_owner_owner_owner_name_alter_flat_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.flat', verbose_name='Квартиры'),
        ),
    ]
