# Generated by Django 4.1.7 on 2023-02-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_alter_owner_flats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
